
// these are the 50 indian cities
export const locations = [
    "Bengaluru",
    "Hyderabad",
    "Pune",
    "Chennai",
    "Gurugram",
    "Noida",
    "Mumbai",
    "Kolkata",
    "Ahmedabad",
    "Jaipur",
    "Chandigarh",
    "Thiruvananthapuram",
    "Indore",
    "Kochi",
    "Nagpur",
    "Lucknow",
    "Coimbatore",
    "Bhubaneswar",
    "Vadodara",
    "Visakhapatnam",
    "Mysore",
    "Bhopal",
    "Surat",
    "Patna",
    "Rajkot",
    "Ludhiana",
    "Agra",
    "Kanpur",
    "Nashik",
    "Faridabad",
    "Meerut",
    "Raipur",
    "Vijayawada",
    "Jabalpur",
    "Gwalior",
    "Madurai",
    "Aurangabad",
    "Dhanbad",
    "Jamshedpur",
    "Amritsar",
    "Allahabad",
    "Ranchi",
    "Howrah",
    "Gandhinagar",
    "Dehradun",
    "Udaipur",
    "Jodhpur",
    "Ghaziabad",
    "Tiruchirappalli",
    "Mangalore"
];


// 20 job roles

export const jobRoles = [
    "Software Engineer",
    "Frontend Developer",
    "Backend Developer",
    "Full Stack Developer",
    "Mobile App Developer",
    "DevOps Engineer",
    "QA Engineer",
    "UI/UX Designer",
    "Data Scientist",
    "Machine Learning Engineer",
    "AI Engineer",
    "Cloud Engineer",
    "Database Administrator",
    "Security Analyst",
    "Web Developer",
    "Game Developer",
    "Embedded Systems Engineer",
    "Network Engineer",
    "Software Architect",
    "Product Manager"
];

